"""
04번 노트북을 기반으로 SOCIETY용 노트북을 생성합니다.
수정 사항:
  - Cell 00: 제목 VLOG -> SOCIETY
  - Cell 04: 경로/설정 (CATEGORY, DATASET_CSV, 루트탐색, FEATURES_CSV 제거)
  - Cell 06: 컬럼명 thumbnail_path->thumbnail_path_x, channel_id->channel_id_x, channel_name->channel_name_x
  - Cell 08: FEATURES_CSV 대신 메인 CSV에서 채널별 피처 집계
"""
import json, sys, copy
sys.stdout.reconfigure(encoding='utf-8')

src = 'c:/Users/user/Desktop/26-1_URP/2_data_analyze_pipeline/04_vlog_backbone_clusterer_selection_feature_interpretation.ipynb'
dst = 'c:/Users/user/Desktop/26-1_URP/2_data_analyze_pipeline/05_society_backbone_clusterer_selection.ipynb'

with open(src, encoding='utf-8') as f:
    nb = json.load(f)

cells = nb['cells']
new_cells = copy.deepcopy(cells)

# ─── Cell 00: 제목 마크다운 ───────────────────────────────────────────────
new_cells[0]['source'] = [
    "# SOCIETY: Backbone × Clusterer Selection with Feature Interpretation\n",
    "\n",
    "이 노트북은 **DINOv2 vs SigLIP2**, **K-means / DBSCAN / HDBSCAN**, **UMAP vs t-SNE**를 단계적으로 비교하고,\n",
    "최종적으로 **어떤 조합을 선택할지 근거(품질/안정성/해석성)**를 시각화 중심으로 제시합니다.\n",
    "\n",
    "**대상 데이터:** `Data/SOCIETY/SOCIETY_final_kr_clean_add_color_text_person_ratio_title.csv`\n",
    "\n",
    "## 실행 원칙\n",
    "- 클러스터링은 **원본 임베딩 공간**에서 수행\n",
    "- UMAP / t-SNE는 **시각화용**\n",
    "- 최종 선택은 단일 지표가 아니라 **품질 + 안정성 + 피처 해석** 종합\n",
]

# ─── Cell 04: 설정 및 경로 ───────────────────────────────────────────────
new_cells[4]['source'] = [
    "from __future__ import annotations\n",
    "\n",
    "import os\n",
    "os.environ.setdefault('KMP_DUPLICATE_LIB_OK', 'TRUE')\n",
    "os.environ.setdefault('OMP_NUM_THREADS', '4')\n",
    "\n",
    "import csv\n",
    "import json\n",
    "import re\n",
    "from collections import defaultdict\n",
    "from dataclasses import dataclass\n",
    "from pathlib import Path\n",
    "from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib import font_manager\n",
    "from PIL import Image\n",
    "\n",
    "from sklearn.cluster import DBSCAN, KMeans\n",
    "from sklearn.manifold import TSNE\n",
    "from sklearn.metrics import (\n",
    "    adjusted_rand_score,\n",
    "    balanced_accuracy_score,\n",
    "    calinski_harabasz_score,\n",
    "    davies_bouldin_score,\n",
    "    normalized_mutual_info_score,\n",
    "    silhouette_score,\n",
    ")\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from scipy.stats import kruskal, chi2_contingency\n",
    "\n",
    "try:\n",
    "    import hdbscan  # type: ignore\n",
    "    HAS_HDBSCAN = True\n",
    "except Exception:\n",
    "    HAS_HDBSCAN = False\n",
    "    print('[warn] hdbscan 미설치: `%pip install hdbscan`')\n",
    "\n",
    "try:\n",
    "    import umap  # type: ignore\n",
    "except Exception as e:\n",
    "    raise RuntimeError('umap-learn 필요: %pip install umap-learn') from e\n",
    "\n",
    "def _try_set_cjk_font() -> None:\n",
    "    plt.rcParams['axes.unicode_minus'] = False\n",
    "    for f in font_manager.fontManager.ttflist:\n",
    "        name = f.name or ''\n",
    "        if any(k in name for k in ('Nanum', 'Noto Sans CJK', 'Malgun', 'AppleGothic', 'Source Han')):\n",
    "            plt.rcParams['font.family'] = name\n",
    "            return\n",
    "\n",
    "_try_set_cjk_font()\n",
    "\n",
    "# ── 프로젝트 루트 자동 탐색 ──────────────────────────────────────────────\n",
    "# SOCIETY CSV가 있는 경로를 기준으로 ROOT를 찾습니다.\n",
    "_SOCIETY_CSV_REL = Path('Data') / 'SOCIETY' / 'SOCIETY_final_kr_clean_add_color_text_person_ratio_title.csv'\n",
    "\n",
    "def _find_root() -> Path:\n",
    "    cwd = Path.cwd().resolve()\n",
    "    for base in [cwd, *cwd.parents]:\n",
    "        if (base / _SOCIETY_CSV_REL).is_file():\n",
    "            return base\n",
    "    # Cursor가 파일 경로로 실행하는 경우 대비: 절대경로 fallback\n",
    "    for nb_path in Path(__file__).resolve().parents if '__file__' in dir() else []:\n",
    "        if (nb_path / _SOCIETY_CSV_REL).is_file():\n",
    "            return nb_path\n",
    "    raise FileNotFoundError(\n",
    "        f'SOCIETY CSV를 찾지 못했습니다.\\n'\n",
    "        f'  탐색한 경로: {cwd} (및 상위 폴더들)\\n'\n",
    "        f'  찾는 파일: {{ROOT}}/{_SOCIETY_CSV_REL}'\n",
    "    )\n",
    "\n",
    "ROOT = _find_root()\n",
    "CATEGORY = 'SOCIETY'\n",
    "DATASET_CSV = ROOT / _SOCIETY_CSV_REL\n",
    "\n",
    "OUT_BASE = ROOT / 'artifacts' / CATEGORY / 'analysis'\n",
    "OUT_TABLES = OUT_BASE / 'tables'\n",
    "OUT_PLOTS  = OUT_BASE / 'plots'\n",
    "OUT_EMB    = OUT_BASE / 'embeddings'\n",
    "for d in (OUT_TABLES, OUT_PLOTS, OUT_EMB):\n",
    "    d.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "BACKBONES = {\n",
    "    'dinov2-base':  'facebook/dinov2-base',\n",
    "    'siglip2-base': 'google/siglip2-base-patch16-224',\n",
    "}\n",
    "\n",
    "DEVICE_EMB         = 'cuda'   # 'cuda' | 'cpu' | 'auto'\n",
    "BATCH_SIZE_EMB     = 32\n",
    "REBUILD_EMBEDDINGS = False    # True 로 바꾸면 기존 .npy 무시하고 재추출\n",
    "\n",
    "RANDOM_STATE    = 42\n",
    "SEEDS_STABILITY = [11, 22, 33, 44, 55]\n",
    "SUBSAMPLE_FRACS = [0.7, 0.8, 0.9]\n",
    "\n",
    "K_RANGE                    = list(range(2, 11))\n",
    "DBSCAN_EPS_LIST            = [0.22, 0.25, 0.28, 0.30, 0.33, 0.36, 0.40]\n",
    "DBSCAN_MIN_SAMPLES_LIST    = [6, 8, 10, 12, 15]\n",
    "HDBSCAN_MIN_CLUSTER_SIZE_LIST = [12, 16, 20, 30, 40]\n",
    "HDBSCAN_MIN_SAMPLES_LIST   = [None, 5, 8, 10]\n",
    "\n",
    "UMAP_NEIGHBORS  = 20\n",
    "UMAP_MIN_DIST   = 0.1\n",
    "TSNE_PERPLEXITY = 30\n",
    "\n",
    "print('ROOT:    ', ROOT)\n",
    "print('DATASET: ', DATASET_CSV)\n",
    "print('OUT_BASE:', OUT_BASE)\n",
]

# ─── Cell 06: 임베딩 추출 (컬럼명 수정) ──────────────────────────────────
new_cells[6]['source'] = [
    "def _write_csv_rows(path: Path, fieldnames: Sequence[str], rows: Iterable[Dict]) -> None:\n",
    "    with path.open('w', encoding='utf-8', newline='') as f:\n",
    "        w = csv.DictWriter(f, fieldnames=fieldnames)\n",
    "        w.writeheader()\n",
    "        for row in rows:\n",
    "            w.writerow(row)\n",
    "\n",
    "\n",
    "def _read_csv_rows(path: Path, encoding: str = 'utf-8') -> List[Dict[str, str]]:\n",
    "    with path.open('r', encoding=encoding, newline='') as f:\n",
    "        return list(csv.DictReader(f))\n",
    "\n",
    "\n",
    "AUTO_REPAIR_MISSING_THUMBNAILS = True\n",
    "THUMBNAIL_REPAIR_TIMEOUT_SEC   = 20\n",
    "THUMBNAIL_REPAIR_RETRIES       = 2\n",
    "\n",
    "\n",
    "def _thumbnail_path_candidates(raw_path: str, root: Path) -> list[Path]:\n",
    "    raw = (raw_path or '').strip().replace('\\\\', os.sep)\n",
    "    if not raw:\n",
    "        return []\n",
    "    p = Path(raw)\n",
    "    candidates: list[Path] = []\n",
    "    if p.is_absolute():\n",
    "        candidates.append(p)\n",
    "    else:\n",
    "        candidates.append(root / p)\n",
    "        parts = p.parts\n",
    "        if parts and parts[0].lower() == 'data':\n",
    "            rel = Path(*parts[1:]) if len(parts) > 1 else Path('.')\n",
    "            candidates.append(root / 'Data' / rel)\n",
    "        candidates.append(root / 'Data' / p)\n",
    "    out: list[Path] = []\n",
    "    seen: set[str] = set()\n",
    "    for c in candidates:\n",
    "        rc = str(c)\n",
    "        if rc not in seen:\n",
    "            seen.add(rc)\n",
    "            out.append(c)\n",
    "    return out\n",
    "\n",
    "\n",
    "def resolve_thumbnail_path(row: dict, root: Path) -> Path | None:\n",
    "    # SOCIETY CSV의 썸네일 경로 컬럼은 'thumbnail_path_x'\n",
    "    raw = (row.get('thumbnail_path_x') or '').strip()\n",
    "    for c in _thumbnail_path_candidates(raw, root):\n",
    "        if c.is_file():\n",
    "            return c\n",
    "    return None\n",
    "\n",
    "\n",
    "def _download_thumbnail_for_row(row: dict, root: Path) -> Path | None:\n",
    "    import requests\n",
    "    if not AUTO_REPAIR_MISSING_THUMBNAILS:\n",
    "        return None\n",
    "    raw = (row.get('thumbnail_path_x') or '').strip()\n",
    "    url = (row.get('thumbnail_url_x') or '').strip()\n",
    "    if not raw or not url:\n",
    "        return None\n",
    "    candidates = _thumbnail_path_candidates(raw, root)\n",
    "    if not candidates:\n",
    "        return None\n",
    "    target = candidates[0]\n",
    "    try:\n",
    "        target.parent.mkdir(parents=True, exist_ok=True)\n",
    "        last_err = None\n",
    "        for _ in range(THUMBNAIL_REPAIR_RETRIES):\n",
    "            try:\n",
    "                resp = requests.get(url, timeout=THUMBNAIL_REPAIR_TIMEOUT_SEC)\n",
    "                resp.raise_for_status()\n",
    "                target.write_bytes(resp.content)\n",
    "                if target.is_file() and target.stat().st_size > 0:\n",
    "                    return target\n",
    "            except Exception as e:\n",
    "                last_err = e\n",
    "        if last_err is not None:\n",
    "            raise last_err\n",
    "    except Exception:\n",
    "        return None\n",
    "    return None\n",
    "\n",
    "\n",
    "@dataclass\n",
    "class LoadedModel:\n",
    "    model_id: str\n",
    "    alias: str\n",
    "    processor: object\n",
    "    model: object\n",
    "    device: str\n",
    "\n",
    "\n",
    "def _resolve_device(requested: str) -> str:\n",
    "    if requested != 'auto':\n",
    "        return requested\n",
    "    try:\n",
    "        import torch\n",
    "        if torch.cuda.is_available():\n",
    "            return 'cuda'\n",
    "    except Exception:\n",
    "        pass\n",
    "    return 'cpu'\n",
    "\n",
    "\n",
    "def _load_transformers_model(alias: str, model_id: str, device: str) -> LoadedModel:\n",
    "    from transformers import AutoImageProcessor, AutoModel, AutoProcessor\n",
    "    model = AutoModel.from_pretrained(model_id)\n",
    "    try:\n",
    "        processor = AutoProcessor.from_pretrained(model_id)\n",
    "    except Exception:\n",
    "        processor = AutoImageProcessor.from_pretrained(model_id)\n",
    "    model = model.to(device).eval()\n",
    "    return LoadedModel(model_id=model_id, alias=alias, processor=processor, model=model, device=device)\n",
    "\n",
    "\n",
    "def _extract_batch_embeddings(loaded: LoadedModel, images: list) -> list[np.ndarray]:\n",
    "    import torch\n",
    "    inputs = loaded.processor(images=images, return_tensors='pt')\n",
    "    inputs = {k: v.to(loaded.device) for k, v in inputs.items() if isinstance(v, torch.Tensor)}\n",
    "    with torch.no_grad():\n",
    "        outputs = loaded.model(**inputs)\n",
    "    if hasattr(outputs, 'last_hidden_state') and outputs.last_hidden_state is not None:\n",
    "        emb = outputs.last_hidden_state[:, 0, :]\n",
    "    elif hasattr(outputs, 'pooler_output') and outputs.pooler_output is not None:\n",
    "        emb = outputs.pooler_output\n",
    "    else:\n",
    "        first = outputs[0] if isinstance(outputs, (tuple, list)) else None\n",
    "        if first is None:\n",
    "            raise RuntimeError(f'unexpected model output type: {type(outputs)}')\n",
    "        emb = first[:, 0, :] if first.ndim == 3 else first\n",
    "    arr = emb.detach().float().cpu().numpy()\n",
    "    return [arr[i] for i in range(arr.shape[0])]\n",
    "\n",
    "\n",
    "def _is_cuda_related_error(exc: Exception) -> bool:\n",
    "    msg = str(exc).lower()\n",
    "    return any(k in msg for k in ('cuda', 'cudnn', 'nvidia driver', 'no kernel image'))\n",
    "\n",
    "\n",
    "def build_or_load_channel_embeddings(alias: str, model_id: str) -> Tuple[np.ndarray, pd.DataFrame]:\n",
    "    model_dir = OUT_EMB / alias\n",
    "    model_dir.mkdir(parents=True, exist_ok=True)\n",
    "    emb_path  = model_dir / 'channel_embeddings.npy'\n",
    "    meta_path = model_dir / 'channel_metadata.csv'\n",
    "    need = REBUILD_EMBEDDINGS or (not emb_path.is_file()) or (not meta_path.is_file())\n",
    "\n",
    "    if need:\n",
    "        # SOCIETY CSV 컬럼명: channel_id_x, channel_name_x, thumbnail_path_x\n",
    "        rows = _read_csv_rows(DATASET_CSV, encoding='utf-8-sig')\n",
    "        rows = [r for r in rows if (r.get('channel_id_x') or '').strip()]\n",
    "\n",
    "        dev = _resolve_device(DEVICE_EMB)\n",
    "        try:\n",
    "            loaded = _load_transformers_model(alias, model_id, dev)\n",
    "        except Exception as e:\n",
    "            if dev == 'cuda' and _is_cuda_related_error(e):\n",
    "                print(f'[warn] {alias}: CUDA init failed -> fallback to CPU ({e})')\n",
    "                loaded = _load_transformers_model(alias, model_id, 'cpu')\n",
    "            else:\n",
    "                raise\n",
    "\n",
    "        runtime_batch  = BATCH_SIZE_EMB if loaded.device == 'cuda' else min(BATCH_SIZE_EMB, 8)\n",
    "        progress_every = 1 if loaded.device == 'cpu' else 20\n",
    "        print(\n",
    "            f'[extract] {alias} ({loaded.model_id}) on {loaded.device} '\n",
    "            f'/ rows={len(rows)} / batch={runtime_batch} / progress_every={progress_every}'\n",
    "        )\n",
    "\n",
    "        valid_meta: list[Dict[str, str]] = []\n",
    "        emb_list: list[np.ndarray] = []\n",
    "        missing_path_count = 0\n",
    "        missing_path_samples: list[str] = []\n",
    "        open_fail_count = 0\n",
    "\n",
    "        for i in range(0, len(rows), runtime_batch):\n",
    "            chunk = rows[i : i + runtime_batch]\n",
    "            images, metas = [], []\n",
    "            repaired = 0\n",
    "            for r in chunk:\n",
    "                p = resolve_thumbnail_path(r, ROOT)\n",
    "                if p is None:\n",
    "                    p = _download_thumbnail_for_row(r, ROOT)\n",
    "                    if p is not None:\n",
    "                        repaired += 1\n",
    "                if p is None:\n",
    "                    missing_path_count += 1\n",
    "                    raw = str((r.get('thumbnail_path_x') or '')).strip()\n",
    "                    if raw and len(missing_path_samples) < 8:\n",
    "                        missing_path_samples.append(raw)\n",
    "                    continue\n",
    "                try:\n",
    "                    with Image.open(p) as img:\n",
    "                        images.append(img.convert('RGB'))\n",
    "                    metas.append({\n",
    "                        'channel_id':   str(r.get('channel_id_x',   '')).strip(),\n",
    "                        'channel_name': str(r.get('channel_name_x', '')).strip(),\n",
    "                    })\n",
    "                except Exception:\n",
    "                    open_fail_count += 1\n",
    "                    continue\n",
    "            if repaired:\n",
    "                print(f'  repaired thumbnails in chunk: +{repaired}')\n",
    "            if not images:\n",
    "                continue\n",
    "            try:\n",
    "                batch_emb = _extract_batch_embeddings(loaded, images)\n",
    "            except Exception as e:\n",
    "                if loaded.device == 'cuda' and _is_cuda_related_error(e):\n",
    "                    print(f'[warn] CUDA batch failed at row={i} -> CPU')\n",
    "                    loaded = _load_transformers_model(alias, model_id, 'cpu')\n",
    "                    batch_emb = _extract_batch_embeddings(loaded, images)\n",
    "                else:\n",
    "                    raise\n",
    "            emb_list.extend(batch_emb)\n",
    "            valid_meta.extend(metas)\n",
    "            if (i // runtime_batch) % progress_every == 0:\n",
    "                print(f'  progress: {i}/{len(rows)} (device={loaded.device})')\n",
    "\n",
    "        if not emb_list:\n",
    "            raise RuntimeError(\n",
    "                f'no embeddings extracted for {alias}.\\n'\n",
    "                f'missing thumbnail_path_x count={missing_path_count}, open_fail={open_fail_count}\\n'\n",
    "                f'sample missing paths={missing_path_samples[:5]}'\n",
    "            )\n",
    "\n",
    "        X_vid = np.asarray(emb_list, dtype=np.float32)\n",
    "        _write_csv_rows(model_dir / 'video_metadata.csv', ['channel_id', 'channel_name'], valid_meta)\n",
    "        np.save(model_dir / 'video_embeddings.npy', X_vid)\n",
    "\n",
    "        groups: dict[str, list[int]] = defaultdict(list)\n",
    "        ch_name: dict[str, str] = {}\n",
    "        for i, r in enumerate(valid_meta):\n",
    "            cid = str(r['channel_id']).strip()\n",
    "            if not cid:\n",
    "                continue\n",
    "            groups[cid].append(i)\n",
    "            ch_name[cid] = str(r.get('channel_name', '')).strip()\n",
    "\n",
    "        cids = sorted(groups.keys())\n",
    "        X_ch = np.stack([X_vid[groups[c]].mean(axis=0) for c in cids], axis=0)\n",
    "        norms = np.linalg.norm(X_ch, axis=1, keepdims=True)\n",
    "        norms = np.where(norms < 1e-12, 1.0, norms)\n",
    "        X_ch = (X_ch / norms).astype(np.float32)\n",
    "\n",
    "        np.save(emb_path, X_ch)\n",
    "        rows_out = [\n",
    "            {'channel_id': c, 'channel_name': ch_name.get(c, ''), 'n_videos': str(len(groups[c]))}\n",
    "            for c in cids\n",
    "        ]\n",
    "        _write_csv_rows(meta_path, ['channel_id', 'channel_name', 'n_videos'], rows_out)\n",
    "        print(f'  saved: {emb_path} shape={X_ch.shape}')\n",
    "\n",
    "    X = np.load(emb_path).astype(np.float64)\n",
    "    meta = pd.read_csv(meta_path, encoding='utf-8')\n",
    "    meta['channel_id'] = meta['channel_id'].astype(str).str.strip()\n",
    "    assert X.shape[0] == len(meta), (X.shape, len(meta))\n",
    "    return X, meta\n",
    "\n",
    "\n",
    "X_by_backbone:    Dict[str, np.ndarray]    = {}\n",
    "meta_by_backbone: Dict[str, pd.DataFrame] = {}\n",
    "\n",
    "for alias, model_id in BACKBONES.items():\n",
    "    try:\n",
    "        X_, meta_ = build_or_load_channel_embeddings(alias, model_id)\n",
    "        X_by_backbone[alias]    = X_\n",
    "        meta_by_backbone[alias] = meta_\n",
    "    except Exception as e:\n",
    "        print(f'[warn] backbone skip: {alias} ({e})')\n",
    "\n",
    "if not X_by_backbone:\n",
    "    raise RuntimeError('No backbone embeddings are available.')\n",
    "\n",
    "print('available backbones:', list(X_by_backbone.keys()))\n",
]

# ─── Cell 08: 피처 로딩 (FEATURES_CSV 대신 메인 CSV에서 채널별 집계) ────
new_cells[8]['source'] = [
    "# SOCIETY CSV에는 피처가 이미 내장되어 있으므로 채널별로 평균 집계합니다.\n",
    "# 집계 대상 피처 컬럼 (수치형 전체)\n",
    "FEATURE_COLS = [\n",
    "    'saturation_mean', 'saturation_std', 'laba_mean', 'labb_mean',\n",
    "    'color_entropy', 'saturated_ratio',\n",
    "    'red_ratio', 'orange_ratio', 'yellow_ratio', 'green_ratio',\n",
    "    'cyan_ratio', 'blue_ratio', 'purple_ratio', 'pink_ratio',\n",
    "    'text_ratio', 'person_ratio',\n",
    "    'female_pct', 'male_pct',\n",
    "    'age_~17', 'age_18~24', 'age_25~34', 'age_35~44',\n",
    "    'age_45~54', 'age_55~64', 'age_65~',\n",
    "    'clean_title_x_length',\n",
    "]\n",
    "\n",
    "# 원본 CSV 로드 후 채널별 평균\n",
    "_raw = pd.read_csv(DATASET_CSV, encoding='utf-8-sig', low_memory=False)\n",
    "_raw = _raw.rename(columns={'channel_id_x': 'channel_id', 'channel_name_x': 'channel_name'})\n",
    "_raw['channel_id'] = _raw['channel_id'].astype(str).str.strip()\n",
    "\n",
    "# 피처 컬럼 중 실제 존재하는 것만 사용\n",
    "feature_cols = [c for c in FEATURE_COLS if c in _raw.columns]\n",
    "missing_feat = [c for c in FEATURE_COLS if c not in _raw.columns]\n",
    "if missing_feat:\n",
    "    print(f'[warn] 피처 컬럼 없음 (건너뜀): {missing_feat}')\n",
    "\n",
    "# 채널별 피처 평균 집계\n",
    "feat_df = (\n",
    "    _raw.groupby('channel_id', as_index=False)\n",
    "    [['channel_name'] + feature_cols]\n",
    "    .agg({'channel_name': 'first', **{c: 'mean' for c in feature_cols}})\n",
    ")\n",
    "feat_df['channel_id'] = feat_df['channel_id'].astype(str).str.strip()\n",
    "name_col = 'channel_name'\n",
    "feat_ids = set(feat_df['channel_id'].tolist())\n",
    "print(f'채널 수 (피처 집계): {len(feat_df)} | 피처 수: {len(feature_cols)}')\n",
    "\n",
    "common_ids = set(feat_ids)\n",
    "for alias, meta in meta_by_backbone.items():\n",
    "    meta_ids = set(meta['channel_id'].astype(str).tolist())\n",
    "    before = len(common_ids)\n",
    "    common_ids &= meta_ids\n",
    "    print(f'  intersect with {alias}: {before} -> {len(common_ids)} (meta={len(meta_ids)})')\n",
    "\n",
    "common_ids = sorted(common_ids)\n",
    "print(f'공통 채널 수 (피처 & 모든 백본): {len(common_ids)}')\n",
    "if len(common_ids) < 10:\n",
    "    raise RuntimeError(\n",
    "        f'공통 채널이 너무 적습니다 ({len(common_ids)}개). '\n",
    "        f'channel_id 정합성을 확인하세요.'\n",
    "    )\n",
    "\n",
    "# 진단\n",
    "for alias, meta in meta_by_backbone.items():\n",
    "    meta_ids = set(meta['channel_id'].astype(str).tolist())\n",
    "    print(f'  diag {alias}: feature_only={len(feat_ids - meta_ids)}, backbone_only={len(meta_ids - feat_ids)}')\n",
    "\n",
    "# backbone_data 준비\n",
    "backbone_data: Dict[str, Dict[str, Any]] = {}\n",
    "feat_df_idx = feat_df.set_index('channel_id')\n",
    "\n",
    "for alias in X_by_backbone:\n",
    "    X_all = X_by_backbone[alias]\n",
    "    meta  = meta_by_backbone[alias].copy()\n",
    "    meta['channel_id'] = meta['channel_id'].astype(str).str.strip()\n",
    "    id_to_idx = {cid: i for i, cid in enumerate(meta['channel_id'].tolist())}\n",
    "\n",
    "    ordered_ids = [cid for cid in common_ids if (cid in feat_df_idx.index and cid in id_to_idx)]\n",
    "    feat_sub = feat_df_idx.loc[ordered_ids, feature_cols + [name_col]].reset_index()\n",
    "\n",
    "    idx = [id_to_idx[cid] for cid in ordered_ids]\n",
    "    X = X_all[idx].astype(np.float64)\n",
    "    F = feat_sub[feature_cols].apply(pd.to_numeric, errors='coerce').to_numpy(dtype=np.float64)\n",
    "\n",
    "    merged = feat_sub.copy()\n",
    "    merged['channel_name_meta'] = [meta.loc[id_to_idx[cid], 'channel_name'] for cid in ordered_ids]\n",
    "\n",
    "    backbone_data[alias] = {\n",
    "        'X': X,\n",
    "        'F': F,\n",
    "        'merged': merged,\n",
    "        'feature_cols': feature_cols,\n",
    "    }\n",
    "    print(f'  prepared {alias}: X={X.shape}, F={F.shape}, merged={merged.shape}')\n",
    "\n",
    "print('backbones prepared:', list(backbone_data.keys()))\n",
    "print('feature count:', len(feature_cols))\n",
]

# outputs 초기화 (기존 실행 결과 제거)
for idx in [0, 4, 6, 8]:
    if new_cells[idx]['cell_type'] == 'code':
        new_cells[idx]['outputs'] = []
        new_cells[idx]['execution_count'] = None

nb_out = dict(nb)
nb_out['cells'] = new_cells

with open(dst, 'w', encoding='utf-8') as f:
    json.dump(nb_out, f, ensure_ascii=False, indent=1)

print(f"saved: {dst}")
